from . import saas_pricing
from . import saas_wallet
from . import saas_payment
from . import saas_support_plan
from . import saas_addon
from . import saas_instance
from . import res_config_settings
from . import res_partner
from . import saas_plan
from . import saas_compute_tier
from . import account_move
