{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "odoo-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoo-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "odoo-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scheme: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      {{- if .Values.metrics.secure }}
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
{{- end }}
